// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTvDyCn-VD8L7koZufrb6AuM-dXnms2v0',
    appId: '1:288088513521:android:694251ef82d8035de3c250',
    messagingSenderId: '288088513521',
    projectId: 'fcsmadproject',
    databaseURL: 'https://fcsmadproject-default-rtdb.firebaseio.com',
    storageBucket: 'fcsmadproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wCr8gh2h9iAhVpRIvbZanOgmp3oE2-o',
    appId: '1:288088513521:ios:bee8256153b0c750e3c250',
    messagingSenderId: '288088513521',
    projectId: 'fcsmadproject',
    databaseURL: 'https://fcsmadproject-default-rtdb.firebaseio.com',
    storageBucket: 'fcsmadproject.appspot.com',
    androidClientId: '288088513521-fu3g2ofr1g34vcj6l893pf0kggodgm95.apps.googleusercontent.com',
    iosClientId: '288088513521-kgs0pdh8v7i0hclhm0oafjf77g8fof4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProject',
  );
}
